---

- hosts: all
  become: true
  tasks:

    - name: update repo
      yum:
        update_cache: true
        state: latest

    - name: install apche1 package
      yum:
        name: httpd
        state: latest

    - name: ping the server
      ping:

