---

- hosts: all
  become: true
  tasks:

    - name: install apche and php package then update the cache.
      yum:
        name: 
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: true

    - name: ping the server
      ping:
