---

- hosts: rhel
  become: true
  tasks:

    - name: start httpd centos
      tags: apache,centos,httd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: ping the server
      ping:
