---

- hosts: all
  become: true
  tasks:
    - name: install updates (fedora)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"
    
    - name: install updates (ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: ping the server
      ping:
